DROP TABLE Sku IF EXISTS;
 
CREATE TABLE Sku(
    ID VARCHAR(10),  
    INVENTORY_ON_HAND INT,  
    MIN_QTY_REQ INT,
    PRICE DOUBLE,
    PRODUCT_LABEL VARCHAR(100),
    PRODUCT_NAME  VARCHAR(100)
) ;